variables:
  CI_DEBUG_SERVICES: "true"


before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl
  - pip3 install pyyaml --break-system-packages
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  - test
  - deploy

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script: |
    python3 build_helper.py docker-compose.yml > /dev/null
    echo $DB_CONFIG | base64 -d > .my.cnf
    docker build -t sc-registry.fredhutch.org/shiny-cromwell:test .
    rm .my.cnf
    docker push sc-registry.fredhutch.org/shiny-cromwell:test
    sleep 5

test:
  stage: test
  services: 
    - name: sc-registry.fredhutch.org/shiny-cromwell:test
      alias: shiny-cromwell
  script: |
    sleep 30
    # docker ps
    # CONTAINER_ID=$(docker ps | grep sc-registry.fredhutch.org__shiny-cromwell- | cut -d' ' -f1)
    # env
    # curl -si http://shiny-cromwell:3838/
    # docker logs $CONTAINER_ID
    curl -sI http://shiny-cromwell:3838 | head -1 | grep -q "200 OK"
     R -q -e 'testthat::test_dir("app/tests/")'


deploy_preview:
  stage: deploy
  only:
    refs:
       - dev
  script:
    - docker tag sc-registry.fredhutch.org/shiny-cromwell:test sc-registry.fredhutch.org/shiny-cromwell-preview:latest
    - docker push sc-registry.fredhutch.org/shiny-cromwell-preview:latest
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - python3 build_helper.py docker-compose-preview.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --prune --with-registry-auth -c - shiny-cromwell-preview
    - rm -f ./sc_swarm_cicd_ssh_key





deploy:
  stage: deploy
  only:
    refs:
       - main
  script:
    - docker tag sc-registry.fredhutch.org/shiny-cromwell:test sc-registry.fredhutch.org/shiny-cromwell:latest
    - docker push sc-registry.fredhutch.org/shiny-cromwell:latest
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - python3 build_helper.py docker-compose.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --prune --with-registry-auth -c - shiny-cromwell
    - rm -f ./sc_swarm_cicd_ssh_key


