before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl
  - pip3 install pyyaml
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  - test
  - deploy
before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl
  - pip3 install pyyaml
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script: |
    python3 build_helper.py docker-compose.yml > /dev/null
    docker build -t sc-registry.fredhutch.org/shiny-cromwell:test .
    docker push sc-registry.fredhutch.org/shiny-cromwell:test
    sleep 5

    - docker build -t sc-registry.fredhutch.org/shiny-cromwell:test .
    - |
        if docker ps -a|tr -s ' '|rev|cut -d ' ' -f 1|rev|grep -q shiny-cromwell
        then
        docker stop shiny-cromwell && docker rm --force shiny-cromwell
        fi
    - docker run -d --name shiny-cromwell -p 3838:3838 sc-registry.fredhutch.org/shiny-cromwell:latest
    - sleep 15 && curl -sI  http://localhost:3838  |head -1|grep -q "200 OK"
    - docker stop shiny-cromwell && docker rm --force shiny-cromwell

test:
  stage: test
  services: 
    - name: sc-registry.fredhutch.org/shiny-cromwell:test
      alias: shiny-cromwell
  script: |
    sleep 30
    # docker ps
    # CONTAINER_ID=$(docker ps | grep sc-registry.fredhutch.org__shiny-cromwell- | cut -d' ' -f1)
    # env
    # curl -si http://shiny-cromwell:3838/
    # docker logs $CONTAINER_ID
    curl -sI http://shiny-cromwell:3838 | head -1 | grep -q "200 OK"

  
deploy:
  only:
    refs:
       - main
  script:
    - docker tag sc-registry.fredhutch.org/shiny-cromwell:test sc-registry.fredhutch.org/shiny-cromwell:latest
    - docker push sc-registry.fredhutch.org/shiny-cromwell:latest
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - python3 build_helper.py docker-compose.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --prune --with-registry-auth -c - shiny-cromwell
    - rm -f ./sc_swarm_cicd_ssh_key


